import type { Config } from "tailwindcss";

export default {
  content: ["./src/**/*.{ts,tsx,js,jsx,mdx}"],
  theme: {
    extend: {
      colors: {
        vijaya: {
          red: "#D8261A",
          redDeep: "#B81E14",
          cream: "#FBF6EE",
          sand: "#F3EADB",
          ink: "#1E1A14",
          leaf: "#2C6E3E",
          leafDeep: "#1F5530",
          milk: "#FFFDF8",
          border: "#E9DFCB",
          blue: "#1B61D6",
          blueDeep: "#1450B0",
          blueSoft: "#4187E8",
          skywash: "#EAF2FE",
          skywashDeep: "#D7E6FB",
          slate: "#1B2942",
          slateMute: "#5B6A85",
          line: "#E3EAF4",
          mint: "#1FB07E",
          forest: "#0F1F18",
          forestDeep: "#081310",
          forestSoft: "#1C3328",
          ivory: "#F7EDD8",
          ivoryDeep: "#EFE2C5",
          gold: "#C9A24E",
          goldSoft: "#E2C383",
          goldDeep: "#9C7B33",
          redWarm: "#C13C2E",
          parchment: "#FAF4E6",
          inkWarm: "#1B130A",
          leafBright: "#2C7A47",
          leafLight: "#E7F1E8",
          leafDeepFlag: "#143E26",
          peacock: "#0F6B6B",
          peacockDeep: "#0A4F4F",
          saffron: "#E89B2B",
          marigold: "#F2B544",
          terracotta: "#C66A3A",
          ochre: "#A87826",
          paperFlag: "#FBF6E7",
          flagLine: "#E0DFC4",
          krishna: "#2E4A7A",
          krishnaDeep: "#1B2E54",
          vermilion: "#C2412B",
          parchmentWarm: "#F6E9CC",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        serif: ["var(--font-serif)", "Georgia", "serif"],
        telugu: ["var(--font-telugu)", "Noto Sans Telugu", "sans-serif"],
      },
      boxShadow: {
        card: "0 1px 0 rgba(30,26,20,0.04), 0 12px 28px -18px rgba(30,26,20,0.18)",
        soft: "0 1px 2px rgba(30,26,20,0.04), 0 6px 16px -8px rgba(30,26,20,0.12)",
      },
      backgroundImage: {
        "cream-grad": "linear-gradient(180deg, #FBF6EE 0%, #F6EFE0 100%)",
      },
    },
  },
  plugins: [],
} satisfies Config;
